# fly.toml app configuration file generated for jjnotes-late-butterfly-3194 on 2025-06-21T06:14:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jjnotes-late-butterfly-3194'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[processes]
  app = 'node server.js'

[[mounts]]
  source = 'jjnotes_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
